config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.exists?(params[:id]) ? Kitten.find(params[:id]) : nil
    respond_to do |format|
      format.html
      format.json { render json:@kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    kitten = Kitten.create(kitten_params)
    flash[:notice] = 'New kitten created'
    redirect_to kitten
  end

  def update
    id = params[:id]
    if Kitten.exists?(id)
      kitten = Kitten.find(id)
      kitten.update(kitten_params)
      flash[:notice] = 'Updated kitten'
      redirect_to kitten
    else
      flash[:error] = 'That kitten did not exist'
      redirect_to root_url
    end
  end

  def edit
    @kitten = Kitten.exists?(params[:id]) ? Kitten.find(params[:id]) : nil
  end

  def destroy
    id = params[:id]
    if Kitten.exists?(id)
      Kitten.find(id).destroy
      flash[:notice] = 'Kitten deleted.'
    else
      flash[:error] = 'That kitten does not exist'
    end
    redirect_to root_url
  end

  private
    def kitten_params()
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<p>Name: <%= kitten.name %></p>
<p>Age: <%= kitten.age %></p>
<p>Cuteness: <%= kitten.cuteness %></p>
<p>Softness: <%= kitten.softness %></p>

app/views/kittens/_kitten_form.html.erb
<%= form_for kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :age %>
  <%= f.number_field :age %><br>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %><br>

  <%= f.label :softness%>
  <%= f.text_field :softness%><br>

  <%= f.submit 'Submit Kitten' %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<%= render 'kitten_form', kitten: @kitten %>
<%= link_to 'Delete kitten', kitten_path, method: :delete %>

app/views/kittens/index.html.erb
<% if @kittens.any? %>
  <ul><% @kittens.each do |kitten| %>
    <li><%= render 'kitten', kitten: kitten %>
      <%= link_to "#{kitten.name}'s page", kitten %>
    </li>
  <% end %>
  </ul>
<% else %>
  <h3>There are no kittens here yet!</h3>
  <%= link_to 'Make a new kitten?', new_kitten_path %>
<% end %>

app/views/kittens/new.html.erb
<%= render 'kitten_form', kitten: @kitten %>

app/views/kittens/show.html.erb
<%= render 'kitten', kitten: @kitten %>
<%= link_to 'Edit kitten', edit_kitten_path %>
<%= link_to 'Delete kitten', kitten_path, method: :delete %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation_bar' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

app/views/shared/_navigation_bar.html.erb
<%= link_to 'home', root_path %>
<%= link_to 'New Kitten', new_kitten_path %>